### ISSUE TITLE
Rest Framework

### ISSUE THREAD

**Issue by realxoman** [jayvynl/django-clickhouse-backend#10]
Hi Does this package support Django Rest Framework?

**Comment by realxoman** [comment]
I checked it. and this package support rest Framework.

**Comment by jayvynl** [comment]
> I checked it. and this package support rest Framework.

Most fields support drf, except:

- Enum(8/16)Field
- ArrayField
- TupleField
- MapField

Maybe I will add these serializer field in future release.

**Comment by realxoman** [comment]
@jayvynl Yes, But developer can cast these fields with serializers Fields.

For example I do this and it's work:
casts = serializers.DictField(child=serializers.CharField())
casts_name = serializers.ListField(read_only=True)

Your lib is really helpful for me. Thanks.

**Comment by jayvynl** [comment]
Glat to hear that, you're welcome.
