### ISSUE TITLE
An error occurred in the statement:`Event.objects.filter(content='test') `

### ISSUE THREAD

**Issue by lanfycode** [jayvynl/django-clickhouse-backend#14]
执行filter() update()方法都会报这个错误, 电脑是m1 macbook
![image](https://github.com/jayvynl/django-clickhouse-backend/assets/131220663/6b570f87-6e74-4609-a337-fc4edff893fe)

**Comment by jayvynl** [comment]
猜测可能是由于clickhouse_driver版本导致的，请提供一下：
python 版本
django 版本
django-clickhouse-backend 版本
clickhouse server 版本

**Comment by lanfycode** [comment]
感谢大佬解答，我的clickhouse-driver==0.2.6，难怪我在重新创建虚拟环境后，重新安装库后没有出现问题。
