### ISSUE TITLE
在 migrations 中不能使用 RunPython 或者 RunSQL

### ISSUE THREAD

**Issue by magichuang77** [jayvynl/django-clickhouse-backend#15]
你好  还有一个问题想请教下~  我在 migrations 中想使用 RunPython 或者 RunSQL，如下：
```
def forwards(apps, schema_editor):
    # 其他处理
    pass


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        #  migrations.CreateModel 
        migrations.RunPython(forwards),
    ]
```
django settings 中 DATABASE 有两个，postgres(default) 和 clickhouse
在执行 `python manage.py migrate` 时，`migrations.RunPython` 会被运行；执行 `python manage.py migrate --database clickhouse` 时只会运行 `migrations.CreateModel ` 部分，`migrations.RunPython` 不会被运行

想知道这个是本来就不支持嘛？

**Comment by jayvynl** [comment]
应该都是支持的，出问题的model和migration文件方便贴出来吗

**Comment by magichuang77** [comment]
0001_initial.py
```python
def forwards(apps, schema_editor):
    print("run command")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards),
    ]

```
你好，比如这样写时，`python manage.py migrate --database clickhouse` 不会输出 `run command`

**Comment by magichuang77** [comment]
@jayvynl  你好  辛苦看一下这个现象~

**Comment by jayvynl** [comment]
> You should specify a "hint" in the declaration of the `RunPython` class object. Something like this:
> 
> ```python
> # your_migration.py
> ...
> operations = [
>     migrations.RunPython(forwards, backwards, hints={'your_clickhouse_db': True})
> ]
> ...
> ```
> 
> This should tell the database router which base to work with.
> 
> See more about hints in Django Docs: https://docs.djangoproject.com/en/4.2/ref/migration-operations/#runpython

Thank you, @Kirill-Lekhov . 

Just for complete, this is closely related to database router. For example, if database router from the document is used, then `hints={'clickhouse': True}` is required. If no database router is used, then no hints is required. Refer to [django source code](https://github.com/django/django/blob/107865780aa44914e21d27fdf4ca269bc61c7f01/django/db/utils.py#L253).

**Comment by magichuang77** [comment]
Thanks~

**Comment by magichuang77** [comment]
Thanks~ It is working as expected.
