### ISSUE TITLE
Add missing function fix_format_for_duration_arithmetic

### ISSUE THREAD

**Issue by filipp-tromzo** [jayvynl/django-clickhouse-backend#22]
Add this into `operations.py`
```
    def format_for_duration_arithmetic(self, sql):
        # https://clickhouse.com/docs/en/sql-reference/data-types/special-data-types/interval
        return "INTERVAL %s MICROSECOND" % sql
```
Without it our project crashing.
And may be you could enable PRs? Planned to create PR but they are disabled.

**Comment by jayvynl** [comment]
You can folllow this thread to open a PR. https://github.com/orgs/community/discussions/22665

**Comment by jayvynl** [comment]
Anyway, can you create an issue about the problem your project faced.
Interval of clickhouse is a special type, so you can not use DurationField in you project.
I am interested in what caused the problem.
