### ISSUE TITLE
[BUG] INSERT...SELECT causes an exception when it does not expect any data

### ISSUE THREAD

**Issue by tinglerock** [jayvynl/django-clickhouse-backend#26]
Thank you for this great package! Superb work.

**Describe the bug**
I am running an raw SQL statement to insert records to one table based on records from another table (INSERT...SELECT). I am passing no data to the execute() statement, but because the statement starts with "INSERT INTO", the backend's client class identifies it as an insert statement that needs data, so it calls `process_insert_query`. This calls `receive_sample_block`, expecting ClickHouse to send a DATA packet. But since ClickHouse does not need any data for the insert, a PROGRESS packet is sent instead. The result is an exception: 

```
Traceback (most recent call last):
  File "zzz/lib/python3.8/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "zzz/lib/python3.8/site-packages/clickhouse_backend/driver/client.py", line 36, in execute
    rv = self.process_insert_query(
  File "zzz/lib/python3.8/site-packages/clickhouse_driver/client.py", line 596, in process_insert_query
    sample_block = self.receive_sample_block()
  File "zzz/lib/python3.8/site-packages/clickhouse_driver/client.py", line 623, in receive_sample_block
    raise errors.UnexpectedPacketFromServerError(message)
clickhouse_driver.errors.UnexpectedPacketFromServerError: Code: 102. Unexpected packet from server localhost:9000 (expected Data, Exception, Log or TableColumns, got Progress)
```
 
The fix should be to call `process_ordinary_query` when the user did not provide any data to insert, even if the statement begins with "INSERT INTO".

**Versions**

- django-clickhouse-backend 1.0.3
- clickhouse-driver 0.2.6
- ClickHouse server 23.3.1
- Python 3.8

**Comment by jayvynl** [comment]
Thanks for the report. This will be fixed soon.
