### ISSUE TITLE
`null=True` wraps field into two `Nullable()`

### ISSUE THREAD

**Issue by utapyngo** [jayvynl/django-clickhouse-backend#3]
There are two places where `field.null` is handled:

        if new_rel.field.null:
            rel_type = "Nullable(%s)" % rel_type

        if field.null:
            sql = "Nullable(%s)" % sql

As a result, I get `Nullable(Nullable(UUID))` which turns into 
>DB::Exception: Nested type Nullable(UUID) cannot be inside Nullable type.

**Comment by jayvynl** [comment]
> There are two places where `field.null` is handled:
> 
> ```
>     if new_rel.field.null:
>         rel_type = "Nullable(%s)" % rel_type
> 
>     if field.null:
>         sql = "Nullable(%s)" % sql
> ```
> 
> As a result, I get `Nullable(Nullable(UUID))` which turns into
> 
> > DB::Exception: Nested type Nullable(UUID) cannot be inside Nullable type.

Feature branch is under development and not usable untils it's merged. But I really appreciate your help!

**Comment by jayvynl** [comment]
v1.0.0 has been released.
