### ISSUE TITLE
[Feature] Support django_migrations on CH cluster

### ISSUE THREAD

**Issue by antoine-gargot** [jayvynl/django-clickhouse-backend#33]
**Describe the bug**
Migrations will be run several times if the Django application connects to a specific cluster shard.

I manually added the table on the cluster to fix the issue:

```
CREATE TABLE IF NOT EXISTS django_migrations_local ON CLUSTER '{cluster}'
(
    `id` Int64,
    `app` FixedString(255),
    `name` FixedString(255),
    `applied` DateTime64(6, 'UTC')
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{cluster}/default/{table}', '{replica}')
ORDER BY id
SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS django_migrations ON CLUSTER '{cluster}' AS django_migrations_local
ENGINE = Distributed('{cluster}', default, django_migrations_local, id);
```

However, this assumes that you have a macro for the cluster name. That way, you ensure the migration data is synced on every shard and every replica.

insert_distributed_sync=1 might be needed before running the migration.

**Comment by jayvynl** [comment]
This project does not support distributed table. The only way to use distributed table is managing table schema yourself and set `managed = False` in Meta class.

But this feature is planned. Several weeks are needed to implement.
