### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by utapyngo** [jayvynl/django-clickhouse-backend#4]
When using an update query on the main (postgres) database, I get the following error:

    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <django.db.models.sql.subqueries.UpdateQuery object at 0x7fa278f94130>
    
        def clone(self):
    >       obj = super().clone()
    E       TypeError: super(type, obj): obj must be an instance or subtype of type
    
    .../lib/python3.10/site-packages/clickhouse_backend/models/sql/query.py:20: TypeError

I believe this code is the reason:
    
    for query_class in [subqueries.UpdateQuery, subqueries.DeleteQuery]:
        for attr in ['clone', 'explain']:
            setattr(query_class, attr, getattr(Query, attr))

**Comment by jayvynl** [comment]
Thanks for the reply, and I will work on this.

**Comment by jayvynl** [comment]
check for recent release, fixed in [#6](https://github.com/jayvynl/django-clickhouse-backend/pull/6).
