### ISSUE TITLE
[BUG] django.core.exceptions.ImproperlyConfigured: DateTimeField must only be used with django clickhouse backend.

### ISSUE THREAD

**Issue by oxpaoff** [jayvynl/django-clickhouse-backend#43]
**Describe the bug**
I get this bug after running **migrate**, in migrations i do not have changes related to ClickhouseModel

**To Reproduce**
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    "clickhouse": {
        "ENGINE": "clickhouse_backend.backend",
        "NAME": os.environ["CLICKHOUSE_NAME"],
        "HOST": os.environ["CLICKHOUSE_HOST"],
        "USER": os.environ["CLICKHOUSE_USER"],
        "PASSWORD": os.environ["CLICKHOUSE_PASSWORD"],
        "PORT": os.environ["CLICKHOUSE_PORT"],
    },
}
DATABASE_ROUTERS = ["configs.settings.dbrouters.ClickHouseRouter"]

ClickHouseRouter is from documentation with no changes

**Expected behavior**
success running migrations

**Versions**

- ClickHouse server version. Version can be obtained by running `SELECT version()` query.
- Python version: 3.10.8
- Clickhouse-driver version.
- Django version.: 4.2.4
- Django clickhouse backend version.:  1.1.1

**Comment by jayvynl** [comment]
Duplicate #41, this will be fix in 1 or 2 days.
