### ISSUE TITLE
请问是否考虑支持物化视图？包括分布式的物化视图哇~

### ISSUE THREAD

**Issue by magichuang77** [jayvynl/django-clickhouse-backend#56]

**Comment by jayvynl** [comment]
暂时没有开发计划了，只修复缺陷

**Comment by jayvynl** [comment]
当前只能自己维护物化视图，通过非管理 Model （managed=False）执行查询:

1. 建立物化视图
2. 由于物化视图中的聚合类型不是普通类型，还需要建立中间查询视图
3. 定义非管理 Model （managed=False）映射到中间查询视图

**Comment by magichuang77** [comment]
感谢~
