### ISSUE TITLE
[DOCS] The changelog does not list version 1.1.4

### ISSUE THREAD

**Issue by ishirav** [jayvynl/django-clickhouse-backend#68]
Seems like a new version was released (1.1.4) but the changelog does not describe it

**Comment by jayvynl** [comment]
I find changelogs are duplicated in `[CHANGELOG.md](https://github.com/jayvynl/django-clickhouse-backend/blob/main/CHANGELOG.md)` and [github release page](https://github.com/jayvynl/django-clickhouse-backend/releases). Maybe I should remove the changelog file.

**Comment by vigneshshettyin** [comment]
Hey @jayvynl any timeline for next release?

**Comment by jayvynl** [comment]
> Hey @jayvynl any timeline for next release?

when implementing cityhash function, maybe this weekend.

**Comment by vigneshshettyin** [comment]
Okay, great. Thanks @jayvynl
