### ISSUE TITLE
How to use distributed reports based on clusters

### ISSUE THREAD

**Issue by glinxx** [jayvynl/django-clickhouse-backend#7]

**Comment by jayvynl** [comment]
Do you mean whether this project support [Distributed Table Engine](https://clickhouse.com/docs/en/engines/table-engines/special/distributed)?

The answer is, there is no direct support for distributed table. 

But you can manage distributed table schema yourself, and create a model with managed set to false, then you can insert or select data with this model.

```python
from clickhouse_backend import models

class Spam(models.ClickhouseModel):
    egg = models.UInt16Field(default=0)
    foo = models.StringField(default='', low_cardinality=True)
    bar = models.StringField(default='')

    class Meta:
        managed = False
```
