### ISSUE TITLE
[BUG] AttributeError: 'ReplicatedReplacingMergeTree' object has no attribute 'expressions'

### ISSUE THREAD

**Issue by magichuang77** [jayvynl/django-clickhouse-backend#76]
**Describe the bug**
Using models.ReplicatedReplacingMergeTree engine reported an error: 

> AttributeError: 'ReplicatedReplacingMergeTree' object has no attribute 'expressions'

**To Reproduce**
```
class Student(models.ClickhouseModel):
    name = models.StringField()
    address = models.StringField()
    score = models.Int8Field()

    class Meta:
        engine = models.ReplicatedReplacingMergeTree(
            "/clickhouse/tables/{uuid}/{shard}",
            "{replica}",
            order_by="id"
        )
        cluster = "cluster"
```

**Expected behavior**
Same as using  models.ReplicatedMergeTree logic

**Versions**

- ClickHouse server version. 23.6.1.1524
- Python version. 3.10
- Clickhouse-driver version. 0.2.6
- Django version.  3.2.9
- Django clickhouse backend version. 1.1.6

**Comment by jayvynl** [comment]
I find new issue when debugging this issue, `ReplicatedReplacingMergeTree` and `ReplacingMergeTree` are not working when the optional parameter [`ver`](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree#ver) exists.

I need more time to solve this.

**Comment by magichuang77** [comment]
Another new issue has been discovered, if configured in the config.xml of Clickhouse
```
    <default_replica_path>/clickhouse/tables/{shard}/{database}/{table}</default_replica_path>
    <default_replica_name>{replica}</default_replica_name>
```
When the parameter is not passed in the ReplicatedReplacingMergeTree() of django, an error will also be reported
```python
# clickhouse_backend/models/engines.py", line 208
TypeError: 'ReplicatedReplacingMergeTree' takes at least 2 arguments (0 given)
```

**Comment by jayvynl** [comment]
@magichuang77 All the bugs mentioned in this post have been fixed. Please install from master branch and verify. If ok, I will release a new version.

**Comment by magichuang77** [comment]
@jayvynl  I used the master branch code, which met my expectations and did not encounter the above issues. Thank you

**Comment by jayvynl** [comment]
> @jayvynl I used the master branch code, which met my expectations and did not encounter the above issues. Thank you

Glat to hear that. Latest version [v1.1.7](https://github.com/jayvynl/django-clickhouse-backend/releases/tag/v1.1.7).
