### ISSUE TITLE
Error. Code 102

### ISSUE THREAD

**Issue by Valeria-N** [jayvynl/django-clickhouse-backend#78]
When executing the command: "python manage.py migrate --database clickhouse" an error occurs
"django.db.utils.OperationalError: Code: 102. Unexpected packet from server localhost:8123 (expected Hello or Exception, got Unknown packet)"

My settings:
INSTALLED_APPS = [
    # ...
    clickhouse_backend,
    # ...
]
DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "test",
        "USER": "postgres",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "5432",
    },
    "clickhouse": {
        "ENGINE": "clickhouse_backend.backend",
        "NAME": "test",
        "HOST": "localhost",
        "PORT": "8123",
        "USER": "default",
        "PASSWORD": "",
    }
}

DATABASE_ROUTERS = ['dbrouters.ClickHouseRouter']

Clickhouse is deployed in a docker container. I have tried different versions.

**Comment by jayvynl** [comment]
Python , Django , clickhouse-driver , django-clickhouse-backend, clickhouse, all of these version are required. minimum reproduce code is helpful.

**Comment by Valeria-N** [comment]
Python 3.7
Django 3.2
clickhouse-driver 0.2.6
django-clickhouse-backend 1.1.7
clickhouse-server 23.x.y.z

models.py:
```python
from clickhouse_backend import models


class MyClickHouseModel(models.ClickhouseModel):
    date_field = models.DateField()
    int_field = models.Int32Field()
    char_field = models.StringField()

    class Meta:
        db_table = 'my_clickhouse_model'
```

dbrouters as readme 
All other settings and code remained unchanged. I have created a new project for testing and trying to connect clickhouse to it

**Comment by jayvynl** [comment]
Clickhouse use port 8123 for HTTP api, [clickhouse_driver](https://github.com/mymarilyn/clickhouse-driver) use ClickHouse TCP Native Protocol, which port is 9000.

So in your `settings.py`, change clickhouse port to 9000.
