### ISSUE TITLE
python manage.py migrate does't create table

### ISSUE THREAD

**Issue by Enzozzzz** [jayvynl/django-clickhouse-backend#8]
I have used ```python manage.py makemigrations ``` to generate migration files, and then ```python manage.py migrate```, but not create table in clickhouse, so what is my problem ?

![image](https://user-images.githubusercontent.com/50570005/236724647-537c4fe6-004b-43ff-979e-35ca83eea346.png)

**Comment by jayvynl** [comment]
If clickhouse does not lay in the "default" DATABASES setting, `--database` option must be provided when migrating. For instance, if example config in the document is used, run `python manage.py migrate --database clickhouse` for migrating.

You can execute `python manage.py migrate --help` to get detailed information.

```shell
$ python manage.py migrate --help
usage: manage.py migrate [-h] [--noinput] [--database DATABASE] [--fake]
                         [--fake-initial] [--plan] [--run-syncdb] [--check]
                         [--prune] [--version] [-v {0,1,2,3}]
                         [--settings SETTINGS] [--pythonpath PYTHONPATH]
                         [--traceback] [--no-color] [--force-color]
                         [--skip-checks]
                         [app_label] [migration_name]

Updates database schema. Manages both apps with migrations and those without.

positional arguments:
  app_label             App label of an application to synchronize the state.
  migration_name        Database state will be brought to the state after that
                        migration. Use the name "zero" to unapply all
                        migrations.

optional arguments:
  -h, --help            show this help message and exit
  --noinput, --no-input
                        Tells Django to NOT prompt the user for input of any
                        kind.
  --database DATABASE   Nominates a database to synchronize. Defaults to the
                        "default" database.
```

**Comment by Enzozzzz** [comment]
> If clickhouse does not lay in the "default" DATABASES setting, `--database` option must be provided when migrating. For instance, if example database setting in the document is used, you should run `python manage.py migrate --database clickhouse` for migrating.
> 
> You can execute `python manage.py migrate --help` to get detailed information.
> 
> ```shell
> $ python manage.py migrate --help
> usage: manage.py migrate [-h] [--noinput] [--database DATABASE] [--fake]
>                          [--fake-initial] [--plan] [--run-syncdb] [--check]
>                          [--prune] [--version] [-v {0,1,2,3}]
>                          [--settings SETTINGS] [--pythonpath PYTHONPATH]
>                          [--traceback] [--no-color] [--force-color]
>                          [--skip-checks]
>                          [app_label] [migration_name]
> 
> Updates database schema. Manages both apps with migrations and those without.
> 
> positional arguments:
>   app_label             App label of an application to synchronize the state.
>   migration_name        Database state will be brought to the state after that
>                         migration. Use the name "zero" to unapply all
>                         migrations.
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   --noinput, --no-input
>                         Tells Django to NOT prompt the user for input of any
>                         kind.
>   --database DATABASE   Nominates a database to synchronize. Defaults to the
>                         "default" database.
> ```

tks, it's done~

**Comment by Enzozzzz** [comment]
another question,

when I set clickhouse as default database,
`
DATABASES = {
    'default': {
        'ENGINE': 'clickhouse_backend.backend',
        'NAME': 'test3',
        'HOST': '127.0.0.1',
        'USER': 'default',
        'PASSWORD': '123456',
        'PORT': 9001,
        'TEST': {
            'fake_transaction': True
        }
    }
}
`
and use clickhouse fields, it still can't create table in databse, so what should i do? tks~
// models.py
`from clickhouse_backend import models


class Dataset(models.ClickhouseModel):
    name = models.StringField(max_length=128, unique=True)
    group = models.Int16Field(max_length=128)
    tag = models.ArrayField(
        models.StringField(max_length=128),
        default=list
    )
    map = models.MapField(
        models.StringField(),
        models.StringField()
    )
    class Meta:
        db_table = 'test_dataset'

    def __str__(self):
        return "Dataset({})".format(self.name)`

**Comment by Enzozzzz** [comment]
another question,

when I set clickhouse as default database,
`
DATABASES = { 
  'default': { 
  'ENGINE': 'clickhouse_backend.backend', 
  'NAME': 'test3', 'HOST': '127.0.0.1', 
  'USER': 'default', 
  'PASSWORD': '123456', 
  'PORT': 9001,
   'TEST': { 'fake_transaction': True } }
 }`
and use clickhouse fields, it still can't create table in databse, so what should i do? tks~
// models.py
`from clickhouse_backend import models

class Dataset(models.ClickhouseModel):
name = models.StringField(max_length=128, unique=True)
group = models.Int16Field(max_length=128)
tag = models.ArrayField(
models.StringField(max_length=128),
default=list
)
map = models.MapField(
models.StringField(),
models.StringField()
)
class Meta:
db_table = 'test_dataset'

def __str__(self):
    return "Dataset({})".format(self.name)`

**Comment by Enzozzzz** [comment]
another question, when i set clickhouse as default database, and use clockhouse fields, it still can't crate tables  when migrate, so what should i do , tks.

# models.py

class Dataset(models.ClickhouseModel):
    name = models.StringField(max_length=128, unique=True)
    map = models.MapField(
        models.StringField(),
        models.StringField()
    )
    class Meta:
        db_table = 'dataset'

    def __str__(self):
        return "Dataset({})".format(self.name)

**Comment by Enzozzzz** [comment]
another question, when i set clickhouse as default database, and use clockhouse fields, it still can't crate tables when migrate, so what should i do , tks. @jayvynl 

models.py
class Dataset(models.ClickhouseModel):
name = models.StringField(max_length=128, unique=True)
map = models.MapField(
models.StringField(),
models.StringField()
)
class Meta:
db_table = 'dataset'

def __str__(self):
    return "Dataset({})".format(self.name)

**Comment by Enzozzzz** [comment]
another question, when i set clickhouse as default database, and use clockhouse fields, it still can't crate tables when migrate, so what should i do , tks. @jayvynl

// models.py
```
class Dataset(models.ClickhouseModel):
    name = models.StringField(max_length=128, unique=True)
    map = models.MapField(
        models.StringField(),
        models.StringField()
    )
    class Meta:
        db_table = 'dataset'

    def str(self):
        return "Dataset({})".format(self.name)
```

**Comment by jayvynl** [comment]
> another question, when i set clickhouse as default database, and use clockhouse fields, it still can't crate tables when migrate, so what should i do , tks. @jayvynl
> 
> // models.py
> 
> ```
> class Dataset(models.ClickhouseModel):
>     name = models.StringField(max_length=128, unique=True)
>     map = models.MapField(
>         models.StringField(),
>         models.StringField()
>     )
>     class Meta:
>         db_table = 'dataset'
> 
>     def str(self):
>         return "Dataset({})".format(self.name)
> ```

Do you use the example settings from the document? If yes, you should remove `DATABASE_ROUTERS` variable from `settings.py`.

**Comment by Enzozzzz** [comment]
> > another question, when i set clickhouse as default database, and use clockhouse fields, it still can't crate tables when migrate, so what should i do , tks. @jayvynl
> > // models.py
> > ```
> > class Dataset(models.ClickhouseModel):
> >     name = models.StringField(max_length=128, unique=True)
> >     map = models.MapField(
> >         models.StringField(),
> >         models.StringField()
> >     )
> >     class Meta:
> >         db_table = 'dataset'
> > 
> >     def str(self):
> >         return "Dataset({})".format(self.name)
> > ```
> 
> Do you use the example settings from the document? If yes, you should remove `DATABASE_ROUTERS` variable from `settings.py`.

tks, it's done!
