### ISSUE TITLE
support for  "prewhere"

### ISSUE THREAD

**Issue by Fleapse** [jayvynl/django-clickhouse-backend#80]
hey, clickhouse lang has "prewhere" condition
is there any way to set this condition using django-clickhouse-backend?
and if there is no such method, is it possible to plan to add it for future releases?

**Comment by jayvynl** [comment]
To support this:
1. Add `prewhere` attribute to `clickhouse_backend.models.sql.query.Query` as a container for prewhere clauses.
2. Add `prewhere` method to `clickhouse_backend.models.query.QuerySet` which update `clickhouse_backend.models.sql.query.Query.prewhere`.
3. Generate prewhere SQL in `clickhouse_backend.models.sql.query.compiler.*Compiler.as_sql`.

This may take some time to implement.
