### ISSUE TITLE
Unable to install the library using pip

### ISSUE THREAD

**Issue by daqo98** [jayvynl/django-clickhouse-backend#83]
**Describe the bug**
Hi, I run `"pip install django-clickhouse-backend"` and I got the following error in both Python 3.8 and 3.11:

```
ERROR: Could not find a version that satisfies the requirement clickhouse-django-backend (from versions: none)
ERROR: No matching distribution found for clickhouse-django-backend
```
Please help

**Comment by daqo98** [comment]
@jayvynl Sorry, I deleted the discussion and opened this issue bc I thought this was a more appropriate space to communicate my issue. Following your solution, I ran `pip3 install django-clickhouse-backend` with the very same error messages as a result.

**Comment by jayvynl** [comment]
its strange that in your error message the package name is `clickhouse-django-backend` instead of `django-clickhouse-backend`, seems that you have mistaken the package name.

**Comment by daqo98** [comment]
Yep, indeed that was the error. Now the installation was successful. Sorry for the inconvenience.
