### ISSUE TITLE
dbrouters.py from pypi.org error

### ISSUE THREAD

**Issue by daqo98** [jayvynl/django-clickhouse-backend#84]
When running `python manage.py runserver` after following the settings example from [https://pypi.org/project/django-clickhouse-backend/](https://pypi.org/project/django-clickhouse-backend/) to configure multiple DBs, I got the  following error:

`/lib/python3.11/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

How to solve it?

Thanks

**Comment by jayvynl** [comment]
have you solved this? can you share the solution？

**Comment by daqo98** [comment]
Yes sure, it was only matter of saving "dbrouters.py" in the right place (at the same level as manage.py) so no need to import it when modifying "settings.py".
