### ISSUE TITLE
[BUG] permanent warnings and reconnects from clickhouse-driver

### ISSUE THREAD

**Issue by SokolovskiR** [jayvynl/django-clickhouse-backend#85]
**Describe the bug**
First of all thank you for this useful library!

We have a Django app running in a docker container and couple times a day we see the following warnings in container logs concerning the connection to cklickhouse from clickhouse-driver. 

<img width="1341" alt="Screenshot 2024-05-31 at 08 56 41" src="https://github.com/jayvynl/django-clickhouse-backend/assets/59457122/454169d5-2e8a-4978-a253-8585d57c1b65">

We use these database settings in django:

```json
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "xxx",
        "USER": os.getenv("POSTGRES_USER", "xxx"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "xxx"),
        "HOST": os.getenv("POSTGRES_HOST", "xxx"),
        "PORT": int(os.getenv("POSTGRES_PORT", "5432"))
    },
    "clickhouse": {
        "ENGINE": "clickhouse_backend.backend",
        "NAME": "default",
        "HOST": os.getenv("CLICKHOUSE_HOST", "xxx"),
        "USER": os.getenv("CLICKHOUSE_USER_P", "xxx"),
        "PASSWORD": os.getenv("CLICKHOUSE_PASSWORD_P", "xxx"),
        "PORT": int(os.getenv("CLICKHOUSE_PORT", "9000"))
    }
}
```

We also have some another python app using clickhouse-driver only, without Django and django-clickhouse-backend and we do not see these warnings there. 

**To Reproduce**
Run a django app in docker container using the specs below.

**Expected behavior**
No such log entries.

**Versions**
- Docker base image for Django container: python:3.11.4-slim
- ClickHouse server version: 24.4.1.2088
- Python version: 3.11.4
- Clickhouse-driver version: 0.2.6
- Django version: 4.2.3 (webserver: daphne==4.0.0)
- Django clickhouse backend version: 1.1.7

**Comment by jayvynl** [comment]
This is ok, because clickhouse connection is reused between queries. If there are no queries for a long time, I guess the connection will be closed by the server.
