### ISSUE TITLE
I have a problem with additional settings

### ISSUE THREAD

**Issue by Faust1234** [jayvynl/django-clickhouse-backend#87]
when I try to execute the query I get an error:
DB::Exception: Cannot modify 'use_client_time_zone' setting in readonly mode.

most likely, this error occurs because of this piece of code (https://github.com/jayvynl/django-clickhouse-backend/blob/main/clickhouse_backend/driver/client.py#L18C9-L18C17) that adds additional settings for clickhouse
I can't change the rules for reading in clickhouse, is it possible to somehow remove them or transfer them through django settings, or maybe the problem is something else
if I make a raw query through clickhouse-driver, everything works correctly

**Comment by jayvynl** [comment]
Try setting `use_client_time_zone` to `False` explicitly.

```python
DATABASES = {
    "default": {
        "ENGINE": "clickhouse_backend.backend",
        "OPTIONS": {
            "settings": {
                "use_client_time_zone": False,
            }
        }
    }
}
```

**Comment by Faust1234** [comment]
yes it works thanks)
