### ISSUE TITLE
[QUESTION] How to pass the `secure` flag using this driver?

### ISSUE THREAD

**Issue by paxw-panevo** [jayvynl/django-clickhouse-backend#89]
What is the `secure` flag equivalent (`cliclickhouse client --host xxx.xxx.xxx.clickhouse.cloud --secure`) for this driver? I can't find any in the docs on how to set this option.

**Comment by jayvynl** [comment]
[clickhouse_driver Client arguments should be contained in `settings` key](https://github.com/jayvynl/django-clickhouse-backend/blob/main/docs/Configurations.md#databases) :

```python
{
  "ENGINE": "clickhouse_backend.backend",
  "settings": {
    "secure": True
  }
}
```

**Comment by mattharley** [comment]
I tried everything and finally got it working by specifying the port as well. So in your example, you'd set the environment variables TIMESERIES_DB_PORT to 9440

**Comment by jayvynl** [comment]
sorry for the late reply, you are right and i have made a mistake, `secure` flag is passed in `OPTIONS`> Looking at the code in this repo, https://github.com/jayvynl/django-clickhouse-backend/blob/8e3f07a7ebf3d6db3c4218f7413d888deb181b34/clickhouse_backend/backend/base.py#L192-L215
> 
> 
> ...and [the clickhouse-driver docs](https://clickhouse-driver.readthedocs.io/en/latest/api.html#clickhouse_driver.Client) which your docs links to[*]
> 
> ![image](https://github.com/jayvynl/django-clickhouse-backend/assets/100712424/e6c2422e-d431-4959-bfb4-a49a91999268)
> ![image](https://github.com/jayvynl/django-clickhouse-backend/assets/100712424/05c79859-025c-4961-b5ea-099fd3706693)
> 
> ...can you confirm that this is the way it should be defined in the django settings?
> 
> ```py
> {
>   "ENGINE": "clickhouse_backend.backend",
>   "OPTIONS": {
>     "secure": True,
>     "settings": {
>       'mutations_sync': 1
>     }
>   }
> }
> ```
> 
> ---
> 
> [*] The docs you linked to goes back to the clickhouse-driver docs:
> ![image](https://github.com/jayvynl/django-clickhouse-backend/assets/100712424/db252a65-d922-4d93-8dd9-c02fc5912c96)
>
