### ISSUE TITLE
[BUG] `DatabaseOperations.last_executed_query()` assumes params is not a mapping

### ISSUE THREAD

**Issue by paxw-panevo** [jayvynl/django-clickhouse-backend#92]
**Describe the bug**
It seems like `DatabaseOperations.last_executed_query()` assumes SQL does not use a mapping for parametrization.

![image](https://github.com/user-attachments/assets/2b98070c-8a63-43d3-bfdc-29eba58c2e80)

**To Reproduce**
Given my SQL query is `SELECT COUNT() from tableName where some_column = %(the_column_value)s` and params is `{"the_column_value": 1}`

I get a `format requires mapping` error. 

**Expected behavior**
Code should handle parametrization via mapping.

**Versions**

- ClickHouse server version. Version can be obtained by running `SELECT version()` query. - clickhouse-server:24.4
- Python version. - 3.9
- Clickhouse-driver version. 0.2.6
- Django version. 4.2.14
- Django clickhouse backend version. 1.1.7

**Comment by paxcodes** [comment]
What is the release schedule like for this package? We need the fix in #93 since SQL logging is critical to our project. No worries if you're busy and won't be able to do it soon. We only need an idea so we can decide how our team can move forward.

Thanks again @jayvynl

**Comment by jayvynl** [comment]
I am planning to support latest version of Django, clickhouse-driver, Python. Then release a version. This may take about two weeks. Currently you can install from the master branch.

**Comment by jayvynl** [comment]
> What is the release schedule like for this package? We need the fix in #93 since SQL logging is critical to our project. No worries if you're busy and won't be able to do it soon. We only need an idea so we can decide how our team can move forward.
> 
> Thanks again @jayvynl

released as v1.3.0
