### ISSUE TITLE
[BUG] Support latest clickhouse driver

### ISSUE THREAD

**Issue by RuslanSibgatulin** [jayvynl/django-clickhouse-backend#94]
**Describe the bug**
The project clearly depends on the clickhouse driver version 0.2.6 while the current version is 0.2.8. Please update dependencies if it possible.

**Comment by jayvynl** [comment]
I am planning to support latest version of Django, clickhouse-driver, Python. Then release a version. This may take about two weeks.

**Comment by jayvynl** [comment]
https://github.com/jayvynl/django-clickhouse-backend/releases/tag/v1.3.0
