### ISSUE TITLE
[QUESTION] Is there a way to specify timezone in DateTime64Field?

### ISSUE THREAD

**Issue by cx-agy** [jayvynl/django-clickhouse-backend#98]
Looks like it's hardcoded to 'UTC'

**Comment by jayvynl** [comment]
> Looks like it's hardcoded to 'UTC'

This is intentional, to be consistent with the behavior of postgresql backend.

**Comment by jayvynl** [comment]
Anyway, do you really need to set timezone in database level? The recommended way to deal with timezone is using `django.utils.timezone` module.
